destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/beast-pdf"
port: 4010
output: pdf
product: beast
print_title: BEAST - Bayesian Evolutionary Analysis Sampling Trees
print_subtitle: version 1.X
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: beast_sidebar
